# Generated by Copilot
"""FastAPI server for integrating the PDF parser backend with the React UI."""

from __future__ import annotations

import os
import tempfile
import threading
import time
import traceback
import uuid
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import fitz
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

import config
from knowledge_builder import build_knowledge_base
from page_processor import process_all_pages
from pdf_analyzer import PageType, analyze_pdf
from vlm_client import set_api_key

MAX_UPLOAD_BYTES = 50 * 1024 * 1024
JOB_WORKERS = 1
UI_DIST_DIR = Path(__file__).resolve().parent / "ui" / "dist"
UI_INDEX_FILE = UI_DIST_DIR / "index.html"
FRONTEND_DIST = Path(__file__).resolve().parent / "ui" / "dist"

app = FastAPI(title="PDF Parser API", version="1.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@dataclass
class JobState:
    job_id: str
    source_file_name: str
    source_pdf_path: str
    status: str = "queued"
    phase: str = "queued"
    progress: int = 0
    message: str = "Job queued"
    logs: list[str] = field(default_factory=list)
    stats: dict[str, int] = field(
        default_factory=lambda: {
            "totalPages": 0,
            "textPages": 0,
            "imagePages": 0,
            "mixedPages": 0,
        }
    )
    output_path: str | None = None
    output_file_name: str | None = None
    selected_page_numbers: list[int] = field(default_factory=list)
    error: str | None = None
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)


_jobs: dict[str, JobState] = {}
_jobs_lock = threading.Lock()
_executor = ThreadPoolExecutor(max_workers=JOB_WORKERS)

if (UI_DIST_DIR / "assets").exists():
    app.mount("/assets", StaticFiles(directory=str(UI_DIST_DIR / "assets")), name="ui-assets")


def _resolve_page_range(spec: str | None, total: int) -> list[int] | None:
    if not spec:
        return None

    pages = set()
    for part in spec.split(","):
        token = part.strip()
        if not token:
            continue
        if "-" in token:
            start_raw, end_raw = token.split("-", 1)
            start = int(start_raw)
            end = int(end_raw)
            if start > end:
                start, end = end, start
            pages.update(range(start, end + 1))
        else:
            pages.add(int(token))

    normalized = sorted(p for p in pages if 1 <= p <= total)
    if not normalized:
        raise ValueError("Page selection is outside the PDF page range")
    return normalized


def _save_upload_file(upload: UploadFile, destination: Path) -> None:
    total = 0
    with destination.open("wb") as handle:
        while True:
            chunk = upload.file.read(1024 * 1024)
            if not chunk:
                break
            total += len(chunk)
            if total > MAX_UPLOAD_BYTES:
                raise HTTPException(status_code=413, detail="PDF exceeds 50MB upload limit")
            handle.write(chunk)

    if total == 0:
        raise HTTPException(status_code=400, detail="Uploaded PDF file is empty")


def _has_pdf_signature(file_path: Path) -> bool:
    with file_path.open("rb") as handle:
        return handle.read(5) == b"%PDF-"


def _append_log(job_id: str, message: str) -> None:
    with _jobs_lock:
        job = _jobs.get(job_id)
        if job is None:
            return
        job.logs.append(message)
        if len(job.logs) > 300:
            job.logs = job.logs[-300:]
        job.updated_at = time.time()


def _update_job(job_id: str, **updates: Any) -> None:
    with _jobs_lock:
        job = _jobs.get(job_id)
        if job is None:
            return
        for key, value in updates.items():
            setattr(job, key, value)
        job.updated_at = time.time()


def _job_snapshot(job: JobState) -> dict[str, Any]:
    return {
        "jobId": job.job_id,
        "sourceFileName": job.source_file_name,
        "status": job.status,
        "phase": job.phase,
        "progress": job.progress,
        "message": job.message,
        "logs": list(job.logs),
        "stats": dict(job.stats),
        "output": {
            "markdownFileName": job.output_file_name,
            "markdownDownloadUrl": (
                f"/api/jobs/{job.job_id}/markdown" if job.output_path else None
            ),
            "pdfDownloadUrl": f"/api/jobs/{job.job_id}/pdf",
            "pageImagesUrl": (
                f"/api/jobs/{job.job_id}/page-images" if job.status == "completed" else None
            ),
        },
        "selectedPageNumbers": list(job.selected_page_numbers),
        "error": job.error,
        "createdAt": job.created_at,
        "updatedAt": job.updated_at,
    }


def _preview_image_path(job_id: str, page_number: int) -> Path:
    preview_dir = Path(config.OUTPUT_DIR) / "jobs" / job_id / "preview"
    preview_dir.mkdir(parents=True, exist_ok=True)
    return preview_dir / f"page_{page_number:04d}.jpg"


def _render_preview_page(source_pdf_path: str, page_number: int, output_path: Path, dpi: int = 140) -> None:
    doc = fitz.open(source_pdf_path)
    try:
        page = doc[page_number - 1]
        scale = dpi / 72.0
        mat = fitz.Matrix(scale, scale)
        pix = page.get_pixmap(matrix=mat, alpha=False)
        pix.save(str(output_path), jpg_quality=88)
    finally:
        doc.close()


def _run_parse_job(
    job_id: str,
    pdf_path: str,
    source_file_name: str,
    api_key: str | None,
    dpi: int | None,
    model: str | None,
    pages_spec: str | None,
) -> None:
    original_api_key = config.GROQ_API_KEY
    original_dpi = config.RASTERIZE_DPI
    original_model = config.VLM_MODEL

    try:
        _update_job(
            job_id,
            status="running",
            phase="analyzing",
            progress=5,
            message="Analyzing PDF structure",
        )
        _append_log(job_id, "Starting document analysis")

        if api_key and api_key.strip():
            set_api_key(api_key)
            _append_log(job_id, "Using API key from UI settings")

        if dpi is not None:
            config.RASTERIZE_DPI = dpi
            _append_log(job_id, f"Rasterization DPI set to {dpi}")

        if model is not None and model.strip():
            config.VLM_MODEL = model.strip()
            _append_log(job_id, f"Vision model set to {config.VLM_MODEL}")

        if not config.GROQ_API_KEY:
            raise RuntimeError("GROQ API key not configured. Set it in .env or UI Settings.")

        analyzed_pages = analyze_pdf(pdf_path, verbose=False)
        selected_pages = analyzed_pages
        if pages_spec and pages_spec.strip():
            selected_numbers = _resolve_page_range(pages_spec, len(analyzed_pages))
            if selected_numbers:
                selected_pages = [p for p in analyzed_pages if p.page_number in selected_numbers]
                _append_log(job_id, f"Filtered pages: {pages_spec}")

        selected_page_numbers = [p.page_number for p in selected_pages]
        _update_job(job_id, selected_page_numbers=selected_page_numbers)

        stats = {
            "totalPages": len(selected_pages),
            "textPages": sum(1 for page in selected_pages if page.page_type == PageType.TEXT),
            "imagePages": sum(1 for page in selected_pages if page.page_type == PageType.IMAGE),
            "mixedPages": sum(1 for page in selected_pages if page.page_type == PageType.MIXED),
        }
        _update_job(job_id, progress=20, stats=stats, message="Analysis complete")
        _append_log(job_id, f"Pages selected: {stats['totalPages']}")

        _update_job(job_id, phase="processing", progress=25, message="Processing pages")
        _append_log(job_id, "Processing pages with VLM pipeline")

        def _progress_callback(done: int, total: int, page_info: Any) -> None:
            base = 25
            span = 60
            progress = base + int((done / max(total, 1)) * span)
            _update_job(job_id, progress=progress, message=f"Processed page {page_info.page_number}")
            _append_log(job_id, f"Page {page_info.page_number}: {page_info.page_type.value}")

        with tempfile.TemporaryDirectory(prefix=f"pdf_parser_{job_id}_") as tmp_dir:
            processed_pages = process_all_pages(
                pdf_path=pdf_path,
                pages=selected_pages,
                tmp_dir=tmp_dir,
                verbose=False,
                progress_callback=_progress_callback,
            )

        _update_job(job_id, phase="building_markdown", progress=90, message="Building markdown")
        _append_log(job_id, "Compiling markdown output")

        output_dir = Path(config.OUTPUT_DIR) / "jobs" / job_id
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"{Path(source_file_name).stem}_knowledge.md"

        final_path = build_knowledge_base(
            pages=processed_pages,
            pdf_path=pdf_path,
            output_path=str(output_path),
        )

        _update_job(
            job_id,
            status="completed",
            phase="completed",
            progress=100,
            message="Parsing completed",
            output_path=final_path,
            output_file_name=Path(final_path).name,
        )
        _append_log(job_id, "Job completed successfully")

    except Exception as exc:
        _update_job(
            job_id,
            status="failed",
            phase="failed",
            progress=100,
            message="Parsing failed",
            error=f"{type(exc).__name__}: {exc}",
        )
        _append_log(job_id, f"Error: {type(exc).__name__}: {exc}")
        _append_log(job_id, traceback.format_exc())
    finally:
        # The parser currently uses global config. Restore process defaults after each job.
        config.RASTERIZE_DPI = original_dpi
        config.VLM_MODEL = original_model
        if config.GROQ_API_KEY != original_api_key:
            set_api_key(original_api_key)


@app.get("/api/health")
def health() -> dict[str, Any]:
    return {
        "status": "ok",
        "hasApiKey": bool(config.GROQ_API_KEY),
        "model": config.VLM_MODEL,
        "dpi": config.RASTERIZE_DPI,
    }


@app.post("/api/jobs", status_code=202)
async def create_job(
    file: UploadFile = File(...),
    apiKey: str | None = Form(default=None),
    dpi: int | None = Form(default=None),
    model: str | None = Form(default=None),
    pages: str | None = Form(default=None),
) -> dict[str, Any]:
    file_name = file.filename or "document.pdf"
    if not file_name.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are supported")

    job_id = uuid.uuid4().hex
    job_dir = Path(config.OUTPUT_DIR) / "jobs" / job_id
    job_dir.mkdir(parents=True, exist_ok=True)

    pdf_path = job_dir / "input.pdf"
    _save_upload_file(file, pdf_path)
    if not _has_pdf_signature(pdf_path):
        raise HTTPException(status_code=400, detail="Uploaded file is not a valid PDF")

    job = JobState(
        job_id=job_id,
        source_file_name=file_name,
        source_pdf_path=str(pdf_path),
        message="Upload complete, waiting for worker",
    )
    with _jobs_lock:
        _jobs[job_id] = job

    _executor.submit(
        _run_parse_job,
        job_id,
        str(pdf_path),
        file_name,
        apiKey,
        dpi,
        model,
        pages,
    )

    return _job_snapshot(job)


@app.get("/api/jobs/{job_id}")
def get_job(job_id: str) -> dict[str, Any]:
    with _jobs_lock:
        job = _jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        return _job_snapshot(job)


@app.get("/api/jobs/{job_id}/result")
def get_job_result(job_id: str) -> dict[str, Any]:
    with _jobs_lock:
        job = _jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        if job.status != "completed" or not job.output_path:
            raise HTTPException(status_code=409, detail="Job has not completed")
        output_path = Path(job.output_path)
        source_name = job.source_file_name
        markdown_file_name = job.output_file_name or output_path.name
        selected_page_numbers = list(job.selected_page_numbers)

    if not output_path.exists():
        raise HTTPException(status_code=404, detail="Output file is missing")

    markdown = output_path.read_text(encoding="utf-8", errors="replace")
    return {
        "jobId": job_id,
        "sourceFileName": source_name,
        "markdownFileName": markdown_file_name,
        "markdown": markdown,
        "selectedPageNumbers": selected_page_numbers,
    }


@app.get("/api/jobs/{job_id}/markdown")
def download_markdown(job_id: str) -> FileResponse:
    with _jobs_lock:
        job = _jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        if job.status != "completed" or not job.output_path:
            raise HTTPException(status_code=409, detail="Job has not completed")
        output_path = Path(job.output_path)
        output_name = job.output_file_name or output_path.name

    if not output_path.exists():
        raise HTTPException(status_code=404, detail="Output file is missing")

    return FileResponse(
        path=str(output_path),
        media_type="text/markdown",
        filename=output_name,
    )


@app.get("/api/jobs/{job_id}/pdf")
def download_source_pdf(job_id: str) -> FileResponse:
    with _jobs_lock:
        job = _jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        source_pdf_path = Path(job.source_pdf_path)
        source_file_name = job.source_file_name

    if not source_pdf_path.exists():
        raise HTTPException(status_code=404, detail="Source PDF is missing")

    return FileResponse(
        path=str(source_pdf_path),
        media_type="application/pdf",
        filename=source_file_name,
    )


@app.get("/api/jobs/{job_id}/page-images")
def list_page_images(job_id: str) -> dict[str, Any]:
    with _jobs_lock:
        job = _jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        if job.status != "completed":
            raise HTTPException(status_code=409, detail="Job has not completed")
        page_numbers = list(job.selected_page_numbers)

    images = [
        {
            "pageNumber": page_number,
            "imageUrl": f"/api/jobs/{job_id}/pages/{page_number}/image",
        }
        for page_number in page_numbers
    ]
    return {
        "jobId": job_id,
        "pages": images,
    }


@app.get("/api/jobs/{job_id}/pages/{page_number}/image")
def get_page_image(job_id: str, page_number: int) -> FileResponse:
    with _jobs_lock:
        job = _jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        if job.status != "completed":
            raise HTTPException(status_code=409, detail="Job has not completed")
        selected_pages = set(job.selected_page_numbers)
        source_pdf_path = Path(job.source_pdf_path)

    if page_number not in selected_pages:
        raise HTTPException(status_code=404, detail="Page image is not available for this job")
    if not source_pdf_path.exists():
        raise HTTPException(status_code=404, detail="Source PDF is missing")

    preview_path = _preview_image_path(job_id, page_number)
    if not preview_path.exists():
        _render_preview_page(str(source_pdf_path), page_number, preview_path)

    return FileResponse(
        path=str(preview_path),
        media_type="image/jpeg",
        filename=preview_path.name,
    )


@app.get("/", include_in_schema=False)
def serve_ui_root() -> Any:
    if UI_INDEX_FILE.exists():
        return FileResponse(path=str(UI_INDEX_FILE), media_type="text/html")
    return {"status": "ok", "message": "UI build not found. Build ui/ first."}


@app.get("/{full_path:path}", include_in_schema=False)
def serve_ui_spa(full_path: str) -> FileResponse:
    if full_path.startswith("api/"):
        raise HTTPException(status_code=404, detail="Not found")

    candidate = UI_DIST_DIR / full_path
    if candidate.exists() and candidate.is_file():
        return FileResponse(path=str(candidate))

    if UI_INDEX_FILE.exists():
        return FileResponse(path=str(UI_INDEX_FILE), media_type="text/html")

    raise HTTPException(status_code=404, detail="UI build not found")


@app.get("/", include_in_schema=False)
def serve_frontend_root() -> FileResponse:
    index_path = FRONTEND_DIST / "index.html"
    if not index_path.exists():
        raise HTTPException(status_code=404, detail="Frontend build not found")
    return FileResponse(path=str(index_path), media_type="text/html")


@app.get("/{full_path:path}", include_in_schema=False)
def serve_frontend_assets(full_path: str) -> FileResponse:
    if full_path.startswith("api/"):
        raise HTTPException(status_code=404, detail="Not found")

    if not FRONTEND_DIST.exists():
        raise HTTPException(status_code=404, detail="Frontend build not found")

    safe_base = FRONTEND_DIST.resolve()
    requested = (FRONTEND_DIST / full_path).resolve()
    if not str(requested).startswith(str(safe_base)):
        raise HTTPException(status_code=404, detail="Not found")

    if requested.is_file():
        return FileResponse(path=str(requested))

    index_path = FRONTEND_DIST / "index.html"
    if not index_path.exists():
        raise HTTPException(status_code=404, detail="Frontend build not found")

    return FileResponse(path=str(index_path), media_type="text/html")


if __name__ == "__main__":
    import uvicorn

    host = os.environ.get("API_HOST", "127.0.0.1")
    port = int(os.environ.get("API_PORT", "8000"))
    uvicorn.run("api_server:app", host=host, port=port, reload=False)
