// Generated by Copilot

export type ParseJobStatus = 'queued' | 'running' | 'completed' | 'failed';

export interface ParseJobStats {
  totalPages: number;
  textPages: number;
  imagePages: number;
  mixedPages: number;
}

export interface ParseJobResponse {
  jobId: string;
  sourceFileName: string;
  status: ParseJobStatus;
  phase: string;
  progress: number;
  message: string;
  logs: string[];
  stats: ParseJobStats;
  output: {
    markdownFileName: string | null;
    markdownDownloadUrl: string | null;
    pdfDownloadUrl: string | null;
    pageImagesUrl: string | null;
  };
  selectedPageNumbers: number[];
  error: string | null;
  createdAt: number;
  updatedAt: number;
}

export interface ParseJobResult {
  jobId: string;
  sourceFileName: string;
  markdownFileName: string;
  markdown: string;
  selectedPageNumbers: number[];
}

export interface PageImage {
  pageNumber: number;
  imageUrl: string;
}

export interface PageImagesResponse {
  jobId: string;
  pages: PageImage[];
}

export interface StartParseJobInput {
  file: File;
  apiKey?: string;
  dpi?: number;
  model?: string;
  pages?: string;
}

const viteEnv = (import.meta as ImportMeta & {
  env?: {
    VITE_BACKEND_URL?: string;
    PROD?: boolean;
  };
}).env;

const defaultBaseUrl =
  viteEnv?.PROD && typeof window !== 'undefined'
    ? window.location.origin
    : 'http://127.0.0.1:8000';

const API_BASE_URL = (viteEnv?.VITE_BACKEND_URL ?? defaultBaseUrl).replace(/\/$/, '');

async function parseErrorMessage(response: Response): Promise<string> {
  try {
    const payload = (await response.json()) as { detail?: string };
    if (payload.detail) {
      return payload.detail;
    }
  } catch {
    // Fall through to status text.
  }

  return `Request failed (${response.status})`;
}

export async function startParseJob(input: StartParseJobInput): Promise<ParseJobResponse> {
  const formData = new FormData();
  formData.append('file', input.file);

  if (input.apiKey) {
    formData.append('apiKey', input.apiKey);
  }
  if (typeof input.dpi === 'number') {
    formData.append('dpi', String(input.dpi));
  }
  if (input.model) {
    formData.append('model', input.model);
  }
  if (input.pages) {
    formData.append('pages', input.pages);
  }

  const response = await fetch(`${API_BASE_URL}/api/jobs`, {
    method: 'POST',
    body: formData,
  });

  if (!response.ok) {
    throw new Error(await parseErrorMessage(response));
  }

  return (await response.json()) as ParseJobResponse;
}

export async function fetchParseJob(jobId: string): Promise<ParseJobResponse> {
  const response = await fetch(`${API_BASE_URL}/api/jobs/${jobId}`);

  if (!response.ok) {
    throw new Error(await parseErrorMessage(response));
  }

  return (await response.json()) as ParseJobResponse;
}

export async function fetchParseResult(jobId: string): Promise<ParseJobResult> {
  const response = await fetch(`${API_BASE_URL}/api/jobs/${jobId}/result`);

  if (!response.ok) {
    throw new Error(await parseErrorMessage(response));
  }

  return (await response.json()) as ParseJobResult;
}

export async function fetchPageImages(jobId: string): Promise<PageImagesResponse> {
  const response = await fetch(`${API_BASE_URL}/api/jobs/${jobId}/page-images`);

  if (!response.ok) {
    throw new Error(await parseErrorMessage(response));
  }

  return (await response.json()) as PageImagesResponse;
}

export function buildApiUrl(path: string): string {
  if (path.startsWith('http://') || path.startsWith('https://')) {
    return path;
  }
  return `${API_BASE_URL}${path.startsWith('/') ? path : `/${path}`}`;
}

export function buildMarkdownDownloadUrl(jobId: string): string {
  return `${API_BASE_URL}/api/jobs/${jobId}/markdown`;
}

export function buildPdfDownloadUrl(jobId: string): string {
  return `${API_BASE_URL}/api/jobs/${jobId}/pdf`;
}

export async function checkBackendHealth(): Promise<boolean> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/health`);
    return response.ok;
  } catch {
    return false;
  }
}
